apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.service.name }}
  labels:
    app: {{ .Values.network.service.name }}
spec:
  ports:
    - port: {{ .Values.network.service.port }}
      targetPort: {{ .Values.network.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.buildlyTemplate.name }}
  type: {{ .Values.network.service.type }}
{{- if eq .Values.network.type "LoadBalancer" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.service.name }}-lb
spec:
  selector:
    app: {{ .Values.network.service.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.network.service.port }}
  type: LoadBalancer
{{- end }}
{{- if eq .Values.network.type "NodePort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.service.name }}-np
spec:
  selector:
    app: {{ .Values.network.service.name }}
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.network.service.port }}
    nodePort: {{ .Values.network.nodeport.port }}
    protocol: TCP
{{- end }}