# buildly-core variables
# It deploys the application
buildly-core:
  replicaCount: 2
  host: define.buildly-core.host.com
  protocol: https
  image:
    repository: index.docker.io/buildly/buildly-core
    tag: latest
  debug: true
  loadinitialdata: true
  loadinitialdataScriptName: loadinitialdata
  admin:
    email: admin@buildly.io
  database:
    name: buildly-core
    port: 5432

defaultFromEmail: support@example.com
defaultOauthDomains: walhall.com,humanitec.com
defaultOrg: Humanitec
defaultReplyTo: noreply@example.com
secrets: "-"
jwtSecrets: buildly-core-test-main-secrets
