# BiFrost variables
# It deploys the application
bifrost:
  replicaCount: 2
  host: define.bifrost.host.com
  protocol: https
  image:
    repository: index.docker.io/buildly/bifrost
    tag: latest
  debug: true
  loadinitialdata: true
  loadinitialdataScriptName: loadinitialdata
  admin:
    email: admin@buildly.io
  database:
    name: bifrost
    port: 5432

defaultFromEmail: support@example.com
defaultOauthDomains: walhall.com,humanitec.com
defaultOrg: Humanitec
defaultReplyTo: noreply@example.com
secrets: "-"
jwtSecrets: bifrost-test-main-secrets
