# buildly variables
# It deploys the application
buildly:
  replicaCount: 2
  host: demo.buildly.io
  protocol: https
  image:
    repository: index.docker.io/buildly/buildly
    tag: latest
  debug: true
  loadinitialdata: true
  loadinitialdataScriptName: loadinitialdata
  admin:
    email: admin@buildly.io
  database:
    name: buildly
    port: 5432

defaultFromEmail: support@buildly.io
defaultOauthDomains: buildly.io
defaultOrg: Buildly
defaultReplyTo: noreply@buildly.io
secrets: "-"
jwtSecrets: buildly-test-main-secrets
