<<<<<<< HEAD
# buildly variables
# It deploys the application
buildly:
  replicaCount: 2
  host: demo.buildly.io
  protocol: https
  image:
    repository: index.docker.io/buildly/buildly
    tag: latest
  debug: true
  loadinitialdata: true
  loadinitialdataScriptName: loadinitialdata
  admin:
    email: admin@buildly.io
  database:
    name: buildly
    port: 5432

# Buildly config map configuration
configmap:
  ACCESS_TOKEN_EXPIRE_SECONDS: "86400"
  ALLOWED_HOSTS: "'*'"
  API_URL: "https://demo.buildly.io"
  CORS_ORIGIN_ALLOW_ALL: "True"
  CORS_ORIGIN_WHITELIST: "'*'"
  DATABASE_ENGINE: postgresql
  DATABASE_HOST: 127.0.0.1
  DATABASE_NAME: buildly
  DATABASE_PORT: "5432"

# Docker registry credentials
dockerregistry:
  name: regcred
  credentials: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImFtVm1iVzkxY21FNk5EQXhNekk1TW1WNE9VRXcifSwicmVnaXN0cnkudG9sYS5pbyI6IHsiYXV0aCI6ICJZV1J0YVc1QWRHOXNZUzVwYnpwb1pXbFFhSFUxZEdocFpXNW5iMnRoYVV3MmRXOXhkVGg1YVRGQ1lUWmhZV2RoYUhCb01HSmxhVkpoYURWNllXVnFaV2x1WjJGcGR6VmphR1ZwZERsbyJ9LCJyZWdpc3RyeS53YWxoYWxsLmlvIjogeyJhdXRoIjogImIyUnBianBYZW1ZcVVrZzVkRE5HIn19LCJIdHRwSGVhZGVycyI6IHsiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjMgKGxpbnV4KSJ9fQ==

# DB credentials and configuration
db_credentials:
  username: cG9zdGdyZXM=
  password: N0xsNnBweHhqbG1xUGYzbQ==

# ingress configuration
ingress:
  name: buildly-ingress
  hosts:
    - demo.buildly.io
  tls:
    - hosts:
        - demo.buildly.io
      secretName: demo.buildly.io
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-demo
    kubernetes.io/ingress.class: "nginx"


defaultFromEmail: support@buildly.io
defaultOauthDomains: buildly.io
defaultOrg: Buildly
defaultReplyTo: noreply@buildly.io
secrets: "-"
jwtSecrets: buildly-test-main-secrets
=======
# buildly deployment configuration
buildly:
  name: buildly-core
  replicaCount: 2
  image:
    repository: index.docker.io/buildly/buildly
    version: latest

network:
  service:
    name: buildly-core-service
    port: 8080
    type: ClusterIP
  ingress:
    name: buildly-core-ingress
    hosts:
      - demo.buildly.io
    tls:
      - hosts:
          - demo.buildly.io
        secretName: demo.buildly.io


# buildly config map configuration
configmap:
  name: buildly-core-configmap
  data:
    ACCESS_TOKEN_EXPIRE_SECONDS: "3600"
    ALLOWED_HOSTS: '*'
    API_URL: "/api"
    CORS_ORIGIN_ALLOW_ALL: "True"
    CORS_ORIGIN_WHITELIST: '*'
    DATABASE_ENGINE: postgresql
    DATABASE_HOST: 127.0.0.1
    DATABASE_NAME: buildly
    DATABASE_PORT: "5432"
    DOCUMENTATION_URL: "https://github.com/buildlyio/buildly-core/blob/master/README.md"
    JWT_ISSUER: "buildly"
    USE_PASSWORD_USER_ATTRIBUTE_SIMILARITY_VALIDATOR: "True"
    USE_PASSWORD_MINIMUM_LENGTH_VALIDATOR: "True"
    PASSWORD_MINIMUM_LENGTH: "6"
    USE_PASSWORD_COMMON_VALIDATOR: "True"
    USE_PASSWORD_NUMERIC_VALIDATOR: "True"

# buildly secrets configuration
# all secret values listed here are for development purpose
secret:
  name: buildly-core-secrets
  data:
    DATABASE_USER: cG9zdGdyZXM=
    DATABASE_PASSWORD: cG9zdGdyZXM=
    JWT_PRIVATE_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLVxuTUlJQk93SUJBQUpCQUxGYzlORlphT2FTd1VNUE5la3RidEpxRWpZWjZJUkJxaHF2SnUxaEtQWW45SFlkNzVjMFxuZ0lEWUhKOWxiN1F3UXZnNDRhTzI3MTA0ckRLMHhTc3R6TDBDQXdFQUFRSkFlNXo1MDk2b3llcUdYNkorUkdHeFxuMTF5dURKN0orME40dHRoVUhTV1dVdGdrZDE5TnZtVE0vbVZMbVBDelpIZ05VVCthV1VLc1E4NCtqaHJ1L05RRFxuMFFJaEFPSE96Rm1qeGpUQVIxanNwbjZZdEpCS1FCNDB0dlQ2V0V2bTJtS20wYUQ3QWlFQXlSUHdYeVpmM0pUK1xuTTZVaTBNdWJzN1FiL0U0ZzFkL2tWTCtvL1hvWkM2Y0NJUUMrbkt6UHRub29LVytRMXlPc2xnZEdEZ2VWOS9YQlxuVWxxYXArTU5oN2hKWlFJZ1pOYU0rd3FobEZ0Yng4YU8yU3Jpb0pJNFhxVkhyam9qcGFTZ09NM2NkWTBDSVFEQlxuUTZja09hRFY5MzdhY21XdWlaaHh1RzJldU5Md05iTWxkdENWNUFEby9nPT1cbi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
    JWT_PUBLIC_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1cbk1Gd3dEUVlKS29aSWh2Y05BUUVCQlFBRFN3QXdTQUpCQUxGYzlORlphT2FTd1VNUE5la3RidEpxRWpZWjZJUkJcbnFocXZKdTFoS1BZbjlIWWQ3NWMwZ0lEWUhKOWxiN1F3UXZnNDRhTzI3MTA0ckRLMHhTc3R6TDBDQXdFQUFRPT1cbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
    SECRET_KEY: ZWsqKWI9bXRjYzdxMWN5bUBvb3gobHlyejFuY3otKHcrKCMmdTdsLSYpN2E4d3YjX2s=

# buildly resources configuration
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

# buildly GCP configuration
gcp:
  enable: False
  cloudsql:
    name: ""
    port: ""
    project_id: ""
    region: ""
    secretName: ""
>>>>>>> 8524f88889a5ff2fe4bb13a63e68cd4cf53d28b0
