# buildly deployment configuration
buildly:
  name: buildly-core
  replicaCount: 2
  image:
    repository: index.docker.io/buildly/buildly
    version: latest

network:
  service:
    name: buildly-core-service
    port: 8080
    type: ClusterIP
  ingress:
    name: buildly-core-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - demo-api.buildly.io
    tls:
      - hosts:
          - demo-api.buildly.io
        secretName: demo-api.buildly.io


# buildly config map configuration
configmap:
  name: buildly-core-configmap
  data:
    ACCESS_TOKEN_EXPIRE_SECONDS: "3600"
    ALLOWED_HOSTS: '*'
    API_URL: "/api"
    CORS_ORIGIN_ALLOW_ALL: "True"
    CORS_ORIGIN_WHITELIST: '*'
    DATABASE_ENGINE: postgresql
    DATABASE_HOST: 127.0.0.1
    DATABASE_NAME: buildly
    DATABASE_PORT: "5432"
    DEBUG: "True"
    DOCUMENTATION_URL: "https://github.com/buildlyio/buildly-core/blob/master/README.md"
    JWT_ISSUER: "buildly"
    USE_PASSWORD_USER_ATTRIBUTE_SIMILARITY_VALIDATOR: "True"
    USE_PASSWORD_MINIMUM_LENGTH_VALIDATOR: "True"
    PASSWORD_MINIMUM_LENGTH: "6"
    USE_PASSWORD_COMMON_VALIDATOR: "True"
    USE_PASSWORD_NUMERIC_VALIDATOR: "True"

# buildly secrets configuration
# all secret values listed here are for development purpose
secret:
  name: buildly-core-secrets
  data:
    DATABASE_USER: cG9zdGdyZXM=
    DATABASE_PASSWORD: cG9zdGdyZXM=
    JWT_PRIVATE_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT3dJQkFBSkJBTEZjOU5GWmFPYVN3VU1QTmVrdGJ0SnFFallaNklSQnFocXZKdTFoS1BZbjlIWWQ3NWMwCmdJRFlISjlsYjdRd1F2ZzQ0YU8yNzEwNHJESzB4U3N0ekwwQ0F3RUFBUUpBZTV6NTA5Nm95ZXFHWDZKK1JHR3gKMTF5dURKN0orME40dHRoVUhTV1dVdGdrZDE5TnZtVE0vbVZMbVBDelpIZ05VVCthV1VLc1E4NCtqaHJ1L05RRAowUUloQU9IT3pGbWp4alRBUjFqc3BuNll0SkJLUUI0MHR2VDZXRXZtMm1LbTBhRDdBaUVBeVJQd1h5WmYzSlQrCk02VWkwTXViczdRYi9FNGcxZC9rVkwrby9Yb1pDNmNDSVFDK25LelB0bm9vS1crUTF5T3NsZ2RHRGdlVjkvWEIKVWxxYXArTU5oN2hKWlFJZ1pOYU0rd3FobEZ0Yng4YU8yU3Jpb0pJNFhxVkhyam9qcGFTZ09NM2NkWTBDSVFEQgpRNmNrT2FEVjkzN2FjbVd1aVpoeHVHMmV1Tkx3TmJNbGR0Q1Y1QURvL2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
    JWT_PUBLIC_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTEZjOU5GWmFPYVN3VU1QTmVrdGJ0SnFFallaNklSQgpxaHF2SnUxaEtQWW45SFlkNzVjMGdJRFlISjlsYjdRd1F2ZzQ0YU8yNzEwNHJESzB4U3N0ekwwQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
    OAUTH_CLIENT_ID: d2tYTGxDOWgzazBqeEl4N29MbGx4cEZWVTg5RHhnaTdPOEZZWnlmWA==
    OAUTH_CLIENT_SECRET: S2lLUmZ0OE1hakxhYlFJZDdwalNzYTNPZnZKQVhOOU5FTmkwdFZSVFgzVmJ0aHI2aUNsRURaWnRieUd1RDlNOFViS3BL
    SECRET_KEY: ZWsqKWI9bXRjYzdxMWN5bUBvb3gobHlyejFuY3otKHcrKCMmdTdsLSYpN2E4d3YjX2s=

# buildly resources configuration
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

# buildly GCP configuration
gcp:
  enable: False
  cloudsql:
    name: ""
    port: ""
    project_id: ""
    region: ""
    secretName: ""
