apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.service.name }}
  labels:
    app: {{ .Values.network.service.name }}
spec:
  ports:
    - port: {{ .Values.network.service.port }}
      targetPort: {{ .Values.network.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.buildlyUi.name }}
  type: {{ .Values.network.service.type }}