apiVersion: v1
name: buildly-ui
home: https://buildly.io/
icon: https://buildly.io/icon.png
version: 0.0.9
appVersion: 1.0
description: Buildly is Software Architecture as a Service
keywords:
- gateway
- user-management
- Rapid-Application-Development
- docker
- javascript
- buildly.io
- react
sources:
- https://github.com/buildlyio/buildly-ui-react
maintainers:
- name: greg-lind
  email: greg@buildly.io
- name: jeferson-moura
  email: jeferson@buildly.io
