# buildly ui deployment configuration
buildlyUi:
  name: buildly-ui
  replicaCount: 2
  image:
    repository: index.docker.io/buildly/buildly-ui
    version: 0.2.0

network:
  service:
    name: buildly-ui-service
    port: 9000
    type: ClusterIP
  ingress:
    name: buildly-ui-ingress
    hosts:
      - demo-app.buildly.io
    tls:
      - hosts:
          - demo-app.buildly.io
        secretName: demo-app.buildly.io


# buildly ui config map configuration
configmap:
  name: buildly-ui-configmap
  data:
    API_URL: "https://demo-api.buildly.io/"
    OAUTH_TOKEN_URL: "https://demo-api.buildly.io/oauth/token/"
    PRODUCTION: "true"

# buildly ui secrets configuration
# all secret values listed here are for development purpose
secret:
  name: buildly-ui-secrets
  data:
    OAUTH_CLIENT_ID: d2tYTGxDOWgzazBqeEl4N29MbGx4cEZWVTg5RHhnaTdPOEZZWnlmWA==

# buildly ui resources configuration
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi
